-- The tenant baseline (orgs + white-label config + file categories) lives in migration
-- 20260603000003_seed_tenants.sql so it always applies on the linked remote — the CLI runs
-- seed.sql only once per project, which silently dropped later changes. Nothing to seed here.
--
-- Artisan logins can't be seeded: auth.users rows come from Supabase Auth (signup / invite),
-- not SQL. After an artisan signs up, link them to a tenant:
--
--   insert into organization_members (organization_id, user_id, role)
--   values ('11111111-1111-1111-1111-111111111111', '<auth-user-uuid>', 'owner');
--
-- Find the uuid in the dashboard (Authentication → Users) or `select id, email from auth.users;`.
